development:
  blockchain_api:
    btc: 'https://api.blockchain.info/mempool/fees'
  taal_api:
    bsv: 'https://mapi.taal.com/mapi/feeQuote'
  etherscan_api:
    eth: 'https://api.etherscan.io/api?module=gastracker&action=gasoracle'
    key: <%= ENV['ETHERSCAN_API_KEY'] %>
  bscscan_api:
    bnb: 'https://api.bscscan.com/api?module=gastracker&action=gasoracle'
    key: <%= ENV['BSCSCAN_API_KEY'] %>

  coincap_api: 'https://api.coincap.io/v2/assets'
